ALTER TYPE "AuditAction" ADD VALUE 'GAME_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'REGISTRATION_CONFIRMED';
ALTER TYPE "AuditAction" ADD VALUE 'WAITLIST_JOINED';
ALTER TYPE "AuditAction" ADD VALUE 'REGISTRATION_CANCELLED';
