import type {
  EventGame,
  Membership,
  Notification,
  Organization,
  OrganizerApplication,
  Payment,
  Profile,
  Refund,
  Registration,
  RegistrationGuest,
  Transfer,
  WaitlistEntry,
} from './types';

const cad = (gross: number) => ({ gross, fee: 0, net: gross, currency: 'CAD' as const });

export const mockProfiles: readonly Profile[] = [
  {
    id: 'usr_daniel_osei',
    displayName: 'Daniel Osei',
    legalName: 'Daniel Osei',
    email: 'daniel.osei@example.ca',
    position: 'Midfielder',
    skillLevel: 'Intermediate',
    city: 'Ottawa, ON',
    memberSince: '2025',
    roles: ['player'],
    reliability: {
      indicator: 'good_standing',
      gamesAttended: 23,
      lateCancels: 1,
      noShows: 0,
      missedPayments: 0,
    },
  },
  {
    id: 'usr_marcus_adeyemi',
    displayName: 'Marcus Adeyemi',
    email: 'marcus.adeyemi@example.ca',
    city: 'Ottawa, ON',
    memberSince: '2024',
    roles: ['player', 'organizer'],
    reliability: {
      indicator: 'good_standing',
      gamesAttended: 41,
      lateCancels: 0,
      noShows: 0,
      missedPayments: 0,
    },
  },
  {
    id: 'usr_sade_okonkwo',
    displayName: 'Sade Okonkwo',
    email: 'sade.okonkwo@example.ca',
    city: 'Toronto, ON',
    memberSince: '2024',
    roles: ['admin'],
    reliability: {
      indicator: 'good_standing',
      gamesAttended: 0,
      lateCancels: 0,
      noShows: 0,
      missedPayments: 0,
    },
  },
  {
    id: 'usr_chris_doyle',
    displayName: 'Chris Doyle',
    email: 'chris.doyle@example.ca',
    city: 'Ottawa, ON',
    memberSince: '2026',
    roles: ['player'],
    reliability: {
      indicator: 'attendance_concern',
      gamesAttended: 9,
      lateCancels: 2,
      noShows: 2,
      missedPayments: 0,
    },
  },
];

export const mockOrganizations: readonly Organization[] = [
  {
    id: 'org_westside',
    name: 'Westside Sunday League',
    handle: 'WSL-4471',
    city: 'Ottawa',
    venueDefault: 'Brewer Park Turf',
    blurb: 'Friendly competitive 7-a-side every week. Bring light and dark.',
    membersCount: 48,
    isPrivate: true,
    requiresApproval: true,
    ownerId: 'usr_marcus_adeyemi',
  },
  {
    id: 'org_glebe',
    name: 'Glebe Indoor 5s',
    handle: 'GLB-2210',
    city: 'Ottawa',
    venueDefault: 'Glebe Community Centre',
    blurb: 'Fast indoor futsal. Non-marking shoes required.',
    membersCount: 32,
    isPrivate: true,
    requiresApproval: false,
    ownerId: 'usr_lena_park',
  },
  {
    id: 'org_centretown',
    name: 'Centretown FC Pickup',
    handle: 'CTN-8839',
    city: 'Ottawa',
    venueDefault: 'Plant Recreation Centre',
    blurb: 'Casual midweek runs for all levels.',
    membersCount: 61,
    isPrivate: true,
    requiresApproval: false,
    ownerId: 'usr_priya_shah',
  },
];

export const mockMemberships: readonly Membership[] = [
  {
    id: 'mem_daniel_westside',
    orgId: 'org_westside',
    userId: 'usr_daniel_osei',
    status: 'active',
    role: 'player',
    permissions: [],
    joinedAt: '2025-11-03T14:00:00.000Z',
  },
  {
    id: 'mem_marcus_westside',
    orgId: 'org_westside',
    userId: 'usr_marcus_adeyemi',
    status: 'active',
    role: 'owner',
    permissions: [
      'manage_events',
      'manage_members',
      'manage_registrations',
      'manage_waitlist',
      'manage_attendance',
      'manage_payments',
      'issue_refunds',
      'send_announcements',
      'view_finances',
      'manage_staff',
      'manage_organization',
    ],
    joinedAt: '2024-08-16T16:00:00.000Z',
  },
  {
    id: 'mem_chris_westside_pending',
    orgId: 'org_westside',
    userId: 'usr_chris_doyle',
    status: 'pending',
    role: 'player',
    permissions: [],
    joinedAt: '2026-06-12T18:10:00.000Z',
  },
];

export const mockEvents: readonly EventGame[] = [
  {
    id: 'evt_sunday_7s',
    orgId: 'org_westside',
    title: 'Sunday Night 7s',
    status: 'almost_full',
    format: '7-a-side',
    skillLevel: 'Intermediate',
    startAt: '2026-06-14T00:00:00.000Z',
    arriveAt: '2026-06-13T23:45:00.000Z',
    durationMin: 90,
    venueTimeZone: 'America/Toronto',
    venue: {
      name: 'Brewer Park Turf',
      address: '170 Hopewell Ave, Ottawa',
      directionsNote: 'Use the south gate near the parking lot.',
    },
    capacity: 14,
    filledCount: 11,
    waitlistCapacity: 6,
    waitlistMode: 'automatic',
    model: 'pay_now',
    price: cad(12),
    allowGuests: true,
    maxGuests: 1,
    transfers: 'allowed',
    transferApproval: 'manual',
    refundPolicy: { type: 'full_before', deadlineHrs: 24 },
    visibility: 'first_photo',
    rules: 'Light and dark shirt. Shin pads recommended. No slide tackles.',
    equipmentNote: 'Bring water.',
    publicCode: 'WSL-G-7741',
  },
  {
    id: 'evt_tuesday_5s',
    orgId: 'org_glebe',
    title: 'Tuesday Indoor 5s',
    status: 'full',
    format: '5-a-side',
    skillLevel: 'All levels',
    startAt: '2026-06-16T23:00:00.000Z',
    arriveAt: '2026-06-16T22:50:00.000Z',
    durationMin: 60,
    venueTimeZone: 'America/Toronto',
    venue: { name: 'Glebe Community Centre', address: '175 Third Ave, Ottawa' },
    capacity: 10,
    filledCount: 10,
    waitlistCapacity: 8,
    waitlistMode: 'automatic',
    model: 'pay_now',
    price: cad(9),
    allowGuests: false,
    maxGuests: 0,
    transfers: 'allowed',
    transferApproval: 'auto',
    refundPolicy: { type: 'full_before', deadlineHrs: 12 },
    visibility: 'first_photo',
    rules: 'Non-marking shoes only. Futsal ball provided.',
    publicCode: 'GLB-G-3320',
  },
  {
    id: 'evt_skills_training',
    orgId: 'org_centretown',
    title: 'Thursday Skills Training',
    status: 'published',
    format: 'Training',
    skillLevel: 'All levels',
    startAt: '2026-06-18T22:30:00.000Z',
    arriveAt: '2026-06-18T22:20:00.000Z',
    durationMin: 90,
    venueTimeZone: 'America/Toronto',
    venue: { name: 'Plant Recreation Centre', address: '930 Somerset St W, Ottawa' },
    capacity: 20,
    filledCount: 13,
    waitlistCapacity: 0,
    waitlistMode: 'manual',
    model: 'free',
    price: cad(0),
    allowGuests: true,
    maxGuests: 2,
    transfers: 'none',
    transferApproval: 'manual',
    refundPolicy: { type: 'organizer_review', deadlineHrs: 0 },
    visibility: 'name_only',
    rules: 'Bring a ball if you have one. Water provided.',
    publicCode: 'CTN-G-5582',
  },
  {
    id: 'evt_saturday_11s',
    orgId: 'org_westside',
    title: 'Saturday Morning 11s',
    status: 'published',
    format: '11-a-side',
    skillLevel: 'Intermediate',
    startAt: '2026-06-20T14:00:00.000Z',
    arriveAt: '2026-06-20T13:40:00.000Z',
    durationMin: 90,
    venueTimeZone: 'America/Toronto',
    venue: { name: "Mooney's Bay Fields", address: '2960 Riverside Dr, Ottawa' },
    capacity: 22,
    filledCount: 18,
    waitlistCapacity: 6,
    waitlistMode: 'manual',
    model: 'pay_later',
    price: cad(15),
    paymentDeadlineHrs: 36,
    allowGuests: true,
    maxGuests: 1,
    transfers: 'allowed',
    transferApproval: 'manual',
    refundPolicy: { type: 'full_before', deadlineHrs: 24 },
    visibility: 'full',
    rules: 'Cleats recommended. Light and dark shirts.',
    publicCode: 'WSL-G-7752',
  },
];

export const mockRegistrations: readonly Registration[] = [
  {
    id: 'reg_daniel_sunday',
    eventId: 'evt_sunday_7s',
    userId: 'usr_daniel_osei',
    regStatus: 'confirmed',
    payStatus: 'paid',
    amountPaid: cad(12),
    paymentMethod: 'apple_pay',
    idempotencyKey: 'reg_daniel_sunday',
    guestCount: 0,
    createdAt: '2026-06-08T14:05:00.000Z',
    updatedAt: '2026-06-08T14:06:00.000Z',
  },
  {
    id: 'reg_daniel_saturday',
    eventId: 'evt_saturday_11s',
    userId: 'usr_daniel_osei',
    regStatus: 'provisional',
    payStatus: 'payment_due',
    paymentDeadlineAt: '2026-06-15T02:00:00.000Z',
    idempotencyKey: 'reg_daniel_saturday',
    guestCount: 1,
    createdAt: '2026-06-13T14:05:00.000Z',
    updatedAt: '2026-06-13T14:05:00.000Z',
  },
  {
    id: 'reg_daniel_tuesday_waitlist',
    eventId: 'evt_tuesday_5s',
    userId: 'usr_daniel_osei',
    regStatus: 'spot_offered',
    payStatus: 'unpaid',
    waitlistPosition: 1,
    offerExpiresAt: '2026-06-13T19:30:00.000Z',
    idempotencyKey: 'reg_daniel_tuesday_waitlist',
    guestCount: 0,
    createdAt: '2026-06-11T12:00:00.000Z',
    updatedAt: '2026-06-13T18:55:00.000Z',
  },
];

export const mockRegistrationGuests: readonly RegistrationGuest[] = [
  {
    id: 'guest_saturday_1',
    registrationId: 'reg_daniel_saturday',
    displayName: 'Kofi Mensah',
  },
];

export const mockWaitlistEntries: readonly WaitlistEntry[] = [
  {
    id: 'wait_daniel_tuesday',
    eventId: 'evt_tuesday_5s',
    userId: 'usr_daniel_osei',
    position: 1,
    status: 'spot_offered',
    offerExpiresAt: '2026-06-13T19:30:00.000Z',
    createdAt: '2026-06-11T12:00:00.000Z',
  },
  {
    id: 'wait_chris_sunday',
    eventId: 'evt_sunday_7s',
    userId: 'usr_chris_doyle',
    position: 1,
    status: 'waitlisted',
    createdAt: '2026-06-12T19:00:00.000Z',
  },
];

export const mockTransfers: readonly Transfer[] = [
  {
    id: 'tr_daniel_saturday',
    eventId: 'evt_saturday_11s',
    fromUserId: 'usr_daniel_osei',
    toTarget: 'waitlist',
    status: 'approval_pending',
    deadlineAt: '2026-06-19T18:00:00.000Z',
    createdAt: '2026-06-13T17:20:00.000Z',
  },
];

export const mockPayments: readonly Payment[] = [
  {
    id: 'pay_daniel_sunday',
    registrationId: 'reg_daniel_sunday',
    userId: 'usr_daniel_osei',
    eventId: 'evt_sunday_7s',
    orgId: 'org_westside',
    amount: cad(12),
    method: 'apple_pay',
    status: 'paid',
    providerIntentId: 'mock_pi_reg_daniel_sunday',
    receiptUrl: 'mock://receipts/reg_daniel_sunday',
    createdAt: '2026-06-08T14:06:00.000Z',
  },
];

export const mockRefunds: readonly Refund[] = [
  {
    id: 'ref_yusuf_sunday',
    paymentId: 'pay_yusuf_sunday',
    amount: cad(12),
    reason: 'Late cancel goodwill exception.',
    status: 'under_review',
    requestedBy: 'usr_yusuf_ali',
    createdAt: '2026-06-13T16:00:00.000Z',
  },
];

export const mockNotifications: readonly Notification[] = [
  {
    id: 'notif_offer_tuesday',
    userId: 'usr_daniel_osei',
    kind: 'offer',
    title: 'A spot opened up - Tuesday Indoor 5s',
    body: "You're next on the waitlist. Accept within the window to claim it.",
    unread: true,
    deepLink: '/games/evt_tuesday_5s/join',
    createdAt: '2026-06-13T18:55:00.000Z',
  },
  {
    id: 'notif_payment_due',
    userId: 'usr_daniel_osei',
    kind: 'reminder',
    title: 'Payment due in 36h',
    body: 'Saturday Morning 11s - pay $15.00 to keep your provisional spot.',
    unread: true,
    deepLink: '/games/evt_saturday_11s/registration',
    createdAt: '2026-06-13T18:10:00.000Z',
  },
  {
    id: 'notif_announce_westside',
    userId: 'usr_daniel_osei',
    kind: 'announce',
    title: 'Westside Sunday League',
    body: 'Light and dark this Sunday - please bring both shirts.',
    unread: false,
    deepLink: '/orgs/org_westside',
    createdAt: '2026-06-13T16:00:00.000Z',
  },
];

export const mockOrganizerApplications: readonly OrganizerApplication[] = [
  {
    id: 'app_glebe',
    userId: 'usr_lena_park',
    legalName: 'Lena Park',
    displayName: 'Lena Park',
    email: 'lena.park@example.ca',
    phone: '+16135550119',
    orgName: 'Glebe Indoor 5s',
    city: 'Ottawa',
    description: 'Weekly indoor pickup group with consistent attendance and paid court rentals.',
    expectedPlayers: 32,
    expectedGames: 8,
    collectsMoney: true,
    verificationStatus: 'provider_stub',
    status: 'verification_pending',
    createdAt: '2026-06-10T11:00:00.000Z',
  },
  {
    id: 'app_riverside',
    userId: 'usr_riverside_owner',
    legalName: 'Mara Liu',
    displayName: 'Mara Liu',
    email: 'mara.liu@example.ca',
    phone: '+16135550142',
    orgName: 'Riverside Rovers',
    city: 'Ottawa',
    description: 'Weekend pickup group expanding from informal chat coordination.',
    expectedPlayers: 27,
    expectedGames: 4,
    collectsMoney: true,
    verificationStatus: 'provider_stub',
    status: 'new',
    createdAt: '2026-06-12T09:00:00.000Z',
  },
];

export const mockStore = {
  me: mockProfiles[0]!,
  profiles: mockProfiles,
  organizations: mockOrganizations,
  memberships: mockMemberships,
  events: mockEvents,
  registrations: mockRegistrations,
  registrationGuests: mockRegistrationGuests,
  waitlistEntries: mockWaitlistEntries,
  transfers: mockTransfers,
  payments: mockPayments,
  refunds: mockRefunds,
  notifications: mockNotifications,
  organizerApplications: mockOrganizerApplications,
} as const;

export function findEvent(eventId: string): EventGame | undefined {
  return mockEvents.find((event) => event.id === eventId);
}

export function findOrganization(orgId: string): Organization | undefined {
  return mockOrganizations.find((org) => org.id === orgId);
}

export function registrationsForEvent(eventId: string): readonly Registration[] {
  return mockRegistrations.filter((registration) => registration.eventId === eventId);
}

export function spotsLeft(event: EventGame): number {
  return Math.max(event.capacity - event.filledCount, 0);
}
